#!/usr/bin/env bun

import {
  lstatSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join, relative, resolve, sep } from "node:path";

const pluginIdPattern = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/u;

export type ProviderPluginCatalogOptions = {
  readonly pluginRoot: string;
  readonly outputPath: string;
  readonly check: boolean;
};

function regularFile(path: string, label: string): void {
  let stats: ReturnType<typeof lstatSync>;
  try {
    stats = lstatSync(path);
  } catch {
    throw new Error(`${label} is missing`);
  }
  if (!stats.isFile() || stats.isSymbolicLink()) {
    throw new Error(`${label} must be a regular non-symlink file`);
  }
}

export function discoverSourceProviderPluginIds(pluginRoot: string): readonly string[] {
  const root = resolve(pluginRoot);
  const ids: string[] = [];
  for (const entry of readdirSync(root).sort((left, right) => left.localeCompare(right, "en"))) {
    if (entry === "AGENTS.md") {
      regularFile(join(root, entry), "provider plugin root guide");
      continue;
    }
    if (!pluginIdPattern.test(entry) || entry.length > 63) {
      throw new Error(`provider plugin root contains an unsafe entry: ${entry}`);
    }
    const directory = join(root, entry);
    const stats = lstatSync(directory);
    if (!stats.isDirectory() || stats.isSymbolicLink()) {
      throw new Error(`provider plugin ${entry} must be a non-symlink directory`);
    }
    regularFile(join(directory, "plugin.ts"), `provider plugin ${entry} entrypoint`);
    ids.push(entry);
  }
  return Object.freeze(ids);
}

function modulePath(outputPath: string, pluginRoot: string, id: string): string {
  const from = resolve(outputPath, "..");
  const target = join(resolve(pluginRoot), id, "plugin");
  const path = relative(from, target).split(sep).join("/");
  return path.startsWith(".") ? path : `./${path}`;
}

export function renderProviderPluginCatalog(
  pluginIds: readonly string[],
  options: Pick<ProviderPluginCatalogOptions, "pluginRoot" | "outputPath">,
): string {
  const imports = pluginIds
    .map((id, index) =>
      `import sourceProviderPlugin${index} from ${JSON.stringify(modulePath(options.outputPath, options.pluginRoot, id))};`)
    .join("\n");
  const entries = pluginIds
    .map((_id, index) => `  sourceProviderPlugin${index},`)
    .join("\n");
  return `// Generated by src/scripts/generate-provider-plugin-catalog.ts.
// Edit src/plugins/*/plugin.ts, then run \`bun run src/scripts/generate-provider-plugin-catalog.ts\`.

import type { ProviderPluginV1 } from "./provider-plugin";
${imports.length === 0 ? "" : `${imports}\n`}
export const generatedProviderPlugins = Object.freeze([
${entries.length === 0 ? "" : `${entries}\n`}] as const satisfies readonly ProviderPluginV1[]);
`;
}

export function generateProviderPluginCatalog(options: ProviderPluginCatalogOptions): {
  readonly pluginIds: readonly string[];
  readonly changed: boolean;
} {
  const pluginIds = discoverSourceProviderPluginIds(options.pluginRoot);
  const expected = renderProviderPluginCatalog(pluginIds, options);
  let existing: string | undefined;
  try {
    existing = readFileSync(options.outputPath, "utf8");
  } catch {
    existing = undefined;
  }
  if (existing === expected) return { pluginIds, changed: false };
  if (options.check) {
    throw new Error(
      "provider plugin catalog is stale; run `bun run src/scripts/generate-provider-plugin-catalog.ts`",
    );
  }
  writeFileSync(options.outputPath, expected, "utf8");
  return { pluginIds, changed: true };
}

function parseArguments(raw: readonly string[]): boolean {
  if (raw.length === 0) return false;
  if (raw.length === 1 && raw[0] === "--check") return true;
  throw new Error(
    "usage: bun run src/scripts/generate-provider-plugin-catalog.ts [--check]",
  );
}

if (import.meta.main) {
  const check = parseArguments(process.argv.slice(2));
  const sourceRoot = resolve(import.meta.dir, "..");
  const result = generateProviderPluginCatalog({
    pluginRoot: join(sourceRoot, "plugins"),
    outputPath: join(sourceRoot, "provider-plugins.generated.ts"),
    check,
  });
  const action = check ? "checked" : result.changed ? "generated" : "unchanged";
  process.stdout.write(`${action} ${result.pluginIds.length} source provider plugins\n`);
}
