import { afterEach, describe, expect, test } from "bun:test";
import {
  chmodSync,
  existsSync,
  linkSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readlinkSync,
  readdirSync,
  rmSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { captureProcessOwnerIdentity } from "../process-identity";
import {
  acquireInstallLease,
  recoverAbandonedInstallStages,
  releaseInstallLease,
  snapshotRetiredInstallMutationClaimForTest,
} from "./recover-install-stages";

const wrenchMarker =
  "# Generated by the Wrench local installer; safe to replace.";
const predecessorMarker =
  "# Generated by skills/oh/scripts/install-local.sh; safe to replace.";
const retiredClaimPrefix = ".wrench-install.retired-claim-";
const retirementId = "00000000-0000-4000-8000-000000000002";
const recoveryScript = join(import.meta.dir, "recover-install-stages.ts");
const roots: string[] = [];

function differentDigest(value: string): string {
  return `${value.startsWith("0") ? "1" : "0"}${value.slice(1)}`;
}

function fileSystemError(code: string): NodeJS.ErrnoException {
  const error: NodeJS.ErrnoException = new Error(`injected ${code}`);
  error.code = code;
  return error;
}

function retiredClaimName(claimId: string): string {
  return `${retiredClaimPrefix}${claimId}-${retirementId}`;
}

function exactLeaseTarget(owner: {
  readonly pid: number;
  readonly bootId: string;
  readonly processStartId: string;
}): string {
  const record = {
    schemaVersion: 1,
    owner,
    token: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  };
  return `wrench-install-lease-v1:${Buffer.from(JSON.stringify(record), "utf8").toString("base64url")}`;
}

function exactClaimTarget(
  claimId: string,
  owner: {
    readonly pid: number;
    readonly bootId: string;
    readonly processStartId: string;
  },
): string {
  const record = {
    schemaVersion: 1,
    kind: "wrench-install-lease-mutation-claim",
    claimId,
    owner,
  };
  return `wrench-install-claim-v1:${Buffer.from(JSON.stringify(record), "utf8").toString("base64url")}`;
}

function directory(): string {
  const root = mkdtempSync(join(tmpdir(), "wrench-install-stage-recovery-test-"));
  chmodSync(root, 0o700);
  roots.push(root);
  return root;
}

function stage(
  root: string,
  name: string,
  marker: string,
  mode: number = 0o600,
): string {
  const path = join(root, name);
  writeFileSync(path, `#!/bin/sh\n${marker}\nexit 0\n`, { mode });
  chmodSync(path, mode);
  return path;
}

async function waitForPath(path: string, label: string): Promise<void> {
  for (let attempt = 0; attempt < 800; attempt += 1) {
    if (existsSync(path)) return;
    await Bun.sleep(25);
  }
  throw new Error(`timed out waiting for ${label}`);
}

afterEach(() => {
  for (const root of roots.splice(0)) {
    rmSync(root, { recursive: true, force: true });
  }
});

describe("abandoned local installer stage recovery", () => {
  test("never removes a stage protected by its exact live owner lease", () => {
    const root = directory();
    const token = acquireInstallLease(root, process.pid);
    const active = stage(root, ".wrench-install.Abc123", wrenchMarker, 0o700);

    expect(() => recoverAbandonedInstallStages(root)).toThrow(
      `another Wrench installer is active with process ${process.pid}`,
    );
    expect(() => acquireInstallLease(root, process.pid)).toThrow(
      `another Wrench installer is active with process ${process.pid}`,
    );
    expect(existsSync(active)).toBeTrue();

    releaseInstallLease(root, process.pid, token);
    expect(recoverAbandonedInstallStages(root)).toBe(1);
    expect(existsSync(active)).toBeFalse();
  });

  test.each(["prior-boot", "reused-pid"] as const)(
    "reclaims an exact stage whose lease records a %s owner identity",
    (scenario) => {
      const root = directory();
      const current = captureProcessOwnerIdentity(process.pid);
      const staleOwner = scenario === "prior-boot"
        ? { ...current, bootId: differentDigest(current.bootId) }
        : { ...current, processStartId: differentDigest(current.processStartId) };
      symlinkSync(
        exactLeaseTarget(staleOwner),
        join(root, ".wrench-install.lease"),
      );
      const abandoned = stage(
        root,
        ".wrench-install.Abc123",
        wrenchMarker,
        0o700,
      );

      expect(recoverAbandonedInstallStages(root)).toBe(1);
      expect(existsSync(abandoned)).toBeFalse();
      expect(readdirSync(root)).not.toContain(".wrench-install.lease");
    },
  );

  test("reclaims a crashed owner's exact lease and stage before acquisition", async () => {
    const root = directory();
    const owner = Bun.spawn(["/bin/sleep", "30"]);
    try {
      acquireInstallLease(root, owner.pid);
      const abandoned = stage(
        root,
        ".wrench-install.Abc123",
        wrenchMarker,
        0o700,
      );

      owner.kill(9);
      expect(await owner.exited).not.toBe(0);

      const successorToken = acquireInstallLease(root, process.pid);
      expect(existsSync(abandoned)).toBeFalse();
      expect(() => recoverAbandonedInstallStages(root)).toThrow(
        `another Wrench installer is active with process ${process.pid}`,
      );
      releaseInstallLease(root, process.pid, successorToken);
    } finally {
      owner.kill(9);
      await owner.exited;
    }
  });

  test("admits exactly one of four simultaneous stale-lease reclaimers", async () => {
    const root = directory();
    const current = captureProcessOwnerIdentity(process.pid);
    symlinkSync(
      exactLeaseTarget({
        ...current,
        processStartId: differentDigest(current.processStartId),
      }),
      join(root, ".wrench-install.lease"),
    );
    const readyDirectory = join(root, "claim-ready");
    const releasePath = join(root, "release-waiting-claims");
    mkdirSync(readyDirectory, { mode: 0o700 });

    const children = Array.from({ length: 4 }, () => {
      const child = Bun.spawn(
        [process.execPath, recoveryScript, "acquire", root, String(process.pid)],
        {
          env: {
            ...process.env,
            NODE_ENV: "test",
            WRENCH_TEST_INSTALL_MUTATION_WAITING_READY_DIRECTORY:
              readyDirectory,
            WRENCH_TEST_INSTALL_MUTATION_WAITING_RELEASE: releasePath,
          },
          stdout: "pipe",
          stderr: "pipe",
        },
      );
      return {
        child,
        stdout: new Response(child.stdout).text(),
        stderr: new Response(child.stderr).text(),
      };
    });
    try {
      for (
        let attempt = 0;
        attempt < 800 && readdirSync(readyDirectory).length !== 4;
        attempt += 1
      ) {
        const exited = children.find((entry) => entry.child.exitCode !== null);
        if (exited !== undefined) {
          throw new Error(
            `waiting-claim helper exited before arbitration: ${await exited.stderr}`,
          );
        }
        await Bun.sleep(25);
      }
      expect(readdirSync(readyDirectory)).toHaveLength(4);
      writeFileSync(releasePath, "release\n", { mode: 0o600 });
      const results = await Promise.all(children.map(async (entry) => ({
        exitCode: await entry.child.exited,
        stdout: await entry.stdout,
        stderr: await entry.stderr,
      })));
      const winners = results.filter((result) => result.exitCode === 0);
      const losers = results.filter((result) => result.exitCode !== 0);
      expect(winners).toHaveLength(1);
      expect(losers).toHaveLength(3);
      const winnerToken = winners[0]!.stdout.trim();
      expect(winnerToken).toMatch(/^[A-Za-z0-9_-]{32}$/u);
      for (const loser of losers) {
        expect(loser.stderr).toContain("another Wrench installer");
      }
      expect(readdirSync(root).some((name) =>
        name.startsWith(".wrench-install.claim-")
        || name.startsWith(".wrench-install.retired-claim-")
      )).toBeFalse();

      releaseInstallLease(root, process.pid, winnerToken);
      expect(readdirSync(root)).not.toContain(".wrench-install.lease");
    } finally {
      for (const entry of children) entry.child.kill(9);
      await Promise.all(children.map((entry) => entry.child.exited));
    }
  }, 30_000);

  test("blocks a successor while a paused release owns mutation arbitration", async () => {
    const root = directory();
    const owner = Bun.spawn(["/bin/sleep", "30"]);
    const readyPath = join(root, "release-ready");
    const releasePath = join(root, "release-release");
    try {
      const token = acquireInstallLease(root, owner.pid);
      const releaseHelper = Bun.spawn(
        [
          process.execPath,
          recoveryScript,
          "release",
          root,
          String(owner.pid),
          token,
        ],
        {
          env: {
            ...process.env,
            NODE_ENV: "test",
            WRENCH_TEST_INSTALL_RELEASE_READY: readyPath,
            WRENCH_TEST_INSTALL_RELEASE_RELEASE: releasePath,
          },
          stdout: "pipe",
          stderr: "pipe",
        },
      );
      const releaseStdout = new Response(releaseHelper.stdout).text();
      const releaseStderr = new Response(releaseHelper.stderr).text();
      try {
        for (
          let attempt = 0;
          attempt < 800 && !existsSync(readyPath);
          attempt += 1
        ) {
          if (releaseHelper.exitCode !== null) {
            throw new Error(
              `lease release helper exited before its barrier: ${await releaseStderr}`,
            );
          }
          await Bun.sleep(25);
        }
        expect(existsSync(readyPath)).toBeTrue();

        owner.kill(9);
        expect(await owner.exited).not.toBe(0);
        expect(() => acquireInstallLease(root, process.pid)).toThrow(
          "another Wrench installer lease mutation helper is active",
        );
        expect(readdirSync(root)).toContain(".wrench-install.lease");

        writeFileSync(releasePath, "release\n", { mode: 0o600 });
        expect(await releaseHelper.exited).toBe(1);
        expect(await releaseStdout).toBe("");
        expect(await releaseStderr).toContain(
          "local installer lease release owner died before removal",
        );

        const successorToken = acquireInstallLease(root, process.pid);
        releaseInstallLease(root, process.pid, successorToken);
        expect(readdirSync(root)).not.toContain(".wrench-install.lease");
        expect(readdirSync(root).some((name) =>
          name.startsWith(".wrench-install.claim-")
          || name.startsWith(".wrench-install.retired-claim-")
        )).toBeFalse();
      } finally {
        releaseHelper.kill(9);
        await releaseHelper.exited;
      }
    } finally {
      owner.kill(9);
      await owner.exited;
    }
  }, 30_000);

  test("recovers a mutation claim whose held helper is killed", async () => {
    const root = directory();
    const readyPath = join(root, "held-ready");
    const releasePath = join(root, "held-release");
    const helper = Bun.spawn([process.execPath, recoveryScript, root], {
      env: {
        ...process.env,
        NODE_ENV: "test",
        WRENCH_TEST_INSTALL_MUTATION_HELD_READY: readyPath,
        WRENCH_TEST_INSTALL_MUTATION_HELD_RELEASE: releasePath,
      },
      stdout: "pipe",
      stderr: "pipe",
    });
    const stdout = new Response(helper.stdout).text();
    const stderr = new Response(helper.stderr).text();
    try {
      await waitForPath(readyPath, "held mutation claim");
      expect(readdirSync(root).some((name) =>
        name.startsWith(".wrench-install.claim-held-")
      )).toBeTrue();
      helper.kill(9);
      expect(await helper.exited).not.toBe(0);
      await Promise.all([stdout, stderr]);

      expect(recoverAbandonedInstallStages(root)).toBe(0);
      expect(readdirSync(root).some((name) =>
        name.startsWith(".wrench-install.claim-")
        || name.startsWith(".wrench-install.retired-claim-")
      )).toBeFalse();
    } finally {
      helper.kill(9);
      await helper.exited;
    }
  }, 30_000);

  test("cleans the maximum exact dead claim set before admitting a successor", () => {
    const root = directory();
    const current = captureProcessOwnerIdentity(process.pid);
    const staleOwner = {
      ...current,
      processStartId: differentDigest(current.processStartId),
    };
    for (let index = 0; index < 64; index += 1) {
      const claimId =
        `00000000-0000-4000-8000-${String(index).padStart(12, "0")}`;
      symlinkSync(
        exactClaimTarget(claimId, staleOwner),
        join(root, `.wrench-install.claim-waiting-${claimId}`),
      );
    }

    expect(recoverAbandonedInstallStages(root)).toBe(0);
    expect(readdirSync(root).some((name) =>
      name.startsWith(".wrench-install.claim-")
      || name.startsWith(".wrench-install.retired-claim-")
    )).toBeFalse();
  });

  test.each([
    [
      ".wrench-install.claim-waiting-00000000-0000-4000-8000-000000000001",
      "mutation claim",
    ],
    [
      ".wrench-install.retired-claim-00000000-0000-4000-8000-000000000001-00000000-0000-4000-8000-000000000002",
      "retired mutation claim",
    ],
  ] as const)("rejects a stable non-symlink %s", (name, label) => {
    const root = directory();
    writeFileSync(join(root, name), "not a symbolic claim\n", { mode: 0o600 });

    expect(() => recoverAbandonedInstallStages(root)).toThrow(
      `local installer ${label} must be an owned exact symbolic claim`,
    );
  });

  test("retries a verified retired-claim readlink EINVAL and observes absence", () => {
    const root = directory();
    const claimId = "00000000-0000-4000-8000-000000000001";
    const name = retiredClaimName(claimId);
    const path = join(root, name);
    symlinkSync(
      exactClaimTarget(claimId, captureProcessOwnerIdentity(process.pid)),
      path,
    );
    let injectRace = true;
    const fileSystem = {
      lstat: (candidate: string) => lstatSync(candidate, { bigint: true }),
      readlink: (candidate: string): string => {
        if (injectRace) {
          injectRace = false;
          unlinkSync(candidate);
          throw fileSystemError("EINVAL");
        }
        return readlinkSync(candidate, "utf8");
      },
    };

    expect(snapshotRetiredInstallMutationClaimForTest(
      root,
      name,
      fileSystem,
    )).toBe("changed");
    expect(snapshotRetiredInstallMutationClaimForTest(
      root,
      name,
      fileSystem,
    )).toBe("absent");
  });

  test("rejects a stable regular retired claim after a readlink EINVAL retry", () => {
    const root = directory();
    const claimId = "00000000-0000-4000-8000-000000000001";
    const name = retiredClaimName(claimId);
    const path = join(root, name);
    symlinkSync(
      exactClaimTarget(claimId, captureProcessOwnerIdentity(process.pid)),
      path,
    );
    let injectRace = true;
    const fileSystem = {
      lstat: (candidate: string) => lstatSync(candidate, { bigint: true }),
      readlink: (candidate: string): string => {
        if (injectRace) {
          injectRace = false;
          unlinkSync(candidate);
          writeFileSync(candidate, "replacement\n", { mode: 0o600 });
          throw fileSystemError("EINVAL");
        }
        return readlinkSync(candidate, "utf8");
      },
    };

    expect(snapshotRetiredInstallMutationClaimForTest(
      root,
      name,
      fileSystem,
    )).toBe("changed");
    expect(() => snapshotRetiredInstallMutationClaimForTest(
      root,
      name,
      fileSystem,
    )).toThrow(
      "local installer retired mutation claim must be an owned exact symbolic claim",
    );
  });

  test("recovers an exact retired claim when its cleanup helper is killed", async () => {
    const root = directory();
    const readyPath = join(root, "retired-ready");
    const releasePath = join(root, "retired-release");
    const helper = Bun.spawn([process.execPath, recoveryScript, root], {
      env: {
        ...process.env,
        NODE_ENV: "test",
        WRENCH_TEST_INSTALL_MUTATION_RETIRED_READY: readyPath,
        WRENCH_TEST_INSTALL_MUTATION_RETIRED_RELEASE: releasePath,
      },
      stdout: "pipe",
      stderr: "pipe",
    });
    const stdout = new Response(helper.stdout).text();
    const stderr = new Response(helper.stderr).text();
    try {
      await waitForPath(readyPath, "retired mutation claim");
      expect(readdirSync(root).some((name) =>
        name.startsWith(".wrench-install.retired-claim-")
      )).toBeTrue();
      helper.kill(9);
      expect(await helper.exited).not.toBe(0);
      await Promise.all([stdout, stderr]);

      expect(recoverAbandonedInstallStages(root)).toBe(0);
      expect(readdirSync(root).some((name) =>
        name.startsWith(".wrench-install.claim-")
        || name.startsWith(".wrench-install.retired-claim-")
      )).toBeFalse();
    } finally {
      helper.kill(9);
      await helper.exited;
    }
  }, 30_000);

  test("removes exact current and predecessor managed private stages only", () => {
    const root = directory();
    const current = stage(root, ".wrench-install.Abc123", wrenchMarker);
    const predecessor = stage(
      root,
      ".oh-install.Z9z9Z9",
      predecessorMarker,
      0o755,
    );
    const shortLookalike = stage(
      root,
      ".wrench-install.Abc12",
      wrenchMarker,
    );
    const longLookalike = stage(
      root,
      ".oh-install.Z9z9Z90",
      predecessorMarker,
    );
    const renamedLookalike = stage(
      root,
      ".io-install.Abc123",
      wrenchMarker,
    );

    expect(recoverAbandonedInstallStages(root)).toBe(2);
    expect(existsSync(current)).toBeFalse();
    expect(existsSync(predecessor)).toBeFalse();
    expect(existsSync(shortLookalike)).toBeTrue();
    expect(existsSync(longLookalike)).toBeTrue();
    expect(existsSync(renamedLookalike)).toBeTrue();
  });

  test("rejects every candidate before deleting any when one is unsafe", () => {
    const root = directory();
    const valid = stage(root, ".wrench-install.Abc123", wrenchMarker);
    const target = stage(root, "ordinary-wrapper", wrenchMarker);
    const linked = join(root, ".oh-install.Z9z9Z9");
    symlinkSync(target, linked);

    expect(() => recoverAbandonedInstallStages(root)).toThrow(
      "is not an owned private bounded regular file",
    );
    expect(existsSync(valid)).toBeTrue();
    expect(existsSync(linked)).toBeTrue();
  });

  test("recovers exact empty and partial stages interrupted before the marker write", () => {
    const root = directory();
    const empty = join(root, ".wrench-install.Abc123");
    writeFileSync(empty, "", { mode: 0o600 });
    const partial = join(root, ".oh-install.Z9z9Z9");
    writeFileSync(partial, "#!/bin/sh\n# Generated by skills/oh/", {
      mode: 0o600,
    });

    expect(recoverAbandonedInstallStages(root)).toBe(2);
    expect(existsSync(empty)).toBeFalse();
    expect(existsSync(partial)).toBeFalse();
  });

  test("rejects unmanaged or loosely permissioned exact stages", () => {
    const unmanagedRoot = directory();
    const unmanaged = stage(
      unmanagedRoot,
      ".wrench-install.Abc123",
      "# not a Wrench marker",
    );
    expect(() => recoverAbandonedInstallStages(unmanagedRoot)).toThrow(
      "is not managed by Wrench",
    );
    expect(existsSync(unmanaged)).toBeTrue();

    const looseRoot = directory();
    const loose = stage(
      looseRoot,
      ".wrench-install.Z9z9Z9",
      wrenchMarker,
      0o755,
    );
    expect(() => recoverAbandonedInstallStages(looseRoot)).toThrow(
      "is not an owned private bounded regular file",
    );
    expect(existsSync(loose)).toBeTrue();

    const directoryRoot = directory();
    const exactDirectory = join(directoryRoot, ".wrench-install.Abc123");
    mkdirSync(exactDirectory, { mode: 0o700 });
    expect(() => recoverAbandonedInstallStages(directoryRoot)).toThrow(
      "is not an owned private bounded regular file",
    );
    expect(existsSync(exactDirectory)).toBeTrue();

    const linkedRoot = directory();
    const linkedSource = stage(linkedRoot, "ordinary-wrapper", wrenchMarker);
    const hardLinked = join(linkedRoot, ".wrench-install.Abc123");
    linkSync(linkedSource, hardLinked);
    expect(() => recoverAbandonedInstallStages(linkedRoot)).toThrow(
      "is not an owned private bounded regular file",
    );
    expect(existsSync(linkedSource)).toBeTrue();
    expect(existsSync(hardLinked)).toBeTrue();
  });

  test("rejects an over-bound exact stage set without deleting it", () => {
    const root = directory();
    const paths = Array.from({ length: 65 }, (_, index) =>
      stage(
        root,
        `.wrench-install.${String(index).padStart(6, "0")}`,
        wrenchMarker,
      )
    );
    expect(() => recoverAbandonedInstallStages(root)).toThrow(
      "more than 64 exact stages",
    );
    expect(paths.every((path) => existsSync(path))).toBeTrue();
  });
});
