// Generated by src/scripts/generate-provider-plugin-catalog.ts.
// Edit src/plugins/*/plugin.ts, then run `bun run src/scripts/generate-provider-plugin-catalog.ts`.

import type { ProviderPluginV1 } from "./provider-plugin";
import sourceProviderPlugin0 from "./plugins/beeper-linked-device/plugin";
import sourceProviderPlugin1 from "./plugins/bluesky-web/plugin";
import sourceProviderPlugin2 from "./plugins/clasificados-web/plugin";
import sourceProviderPlugin3 from "./plugins/github-web/plugin";
import sourceProviderPlugin4 from "./plugins/gmail-official/plugin";
import sourceProviderPlugin5 from "./plugins/hacker-news-web/plugin";
import sourceProviderPlugin6 from "./plugins/imessage-direct/plugin";
import sourceProviderPlugin7 from "./plugins/linkedin-official/plugin";
import sourceProviderPlugin8 from "./plugins/linkedin-web/plugin";
import sourceProviderPlugin9 from "./plugins/meta-web/plugin";
import sourceProviderPlugin10 from "./plugins/reddit-web/plugin";
import sourceProviderPlugin11 from "./plugins/substack-web/plugin";
import sourceProviderPlugin12 from "./plugins/tiktok-web/plugin";
import sourceProviderPlugin13 from "./plugins/twitch-web/plugin";
import sourceProviderPlugin14 from "./plugins/whatsapp-linked-device/plugin";
import sourceProviderPlugin15 from "./plugins/x-official/plugin";
import sourceProviderPlugin16 from "./plugins/x-web/plugin";
import sourceProviderPlugin17 from "./plugins/youtube-web/plugin";

export const generatedProviderPlugins = Object.freeze([
  sourceProviderPlugin0,
  sourceProviderPlugin1,
  sourceProviderPlugin2,
  sourceProviderPlugin3,
  sourceProviderPlugin4,
  sourceProviderPlugin5,
  sourceProviderPlugin6,
  sourceProviderPlugin7,
  sourceProviderPlugin8,
  sourceProviderPlugin9,
  sourceProviderPlugin10,
  sourceProviderPlugin11,
  sourceProviderPlugin12,
  sourceProviderPlugin13,
  sourceProviderPlugin14,
  sourceProviderPlugin15,
  sourceProviderPlugin16,
  sourceProviderPlugin17,
] as const satisfies readonly ProviderPluginV1[]);
